### ISSUE TITLE
Exception in polling

### ISSUE THREAD

**Issue by btiernay** [icgc-dcc/dcc-dev#8]
``````
2016-08-16 13:57:19,437 [http-nio-9000-exec-7] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with p
ath [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
        at org.icgc.dcc.dev.server.jenkins.JenkinsService.isSuccessfulBuild(JenkinsService.java:110)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.icgc.dcc.dev.server.jenkins.JenkinsService.getSuccessfulBuild(JenkinsService.java:96)
        at org.icgc.dcc.dev.server.portal.candidate.PortalCandidateResolver.createCandidate(PortalCandidateResolver.java:82)
        at org.icgc.dcc.dev.server.portal.candidate.PortalCandidateResolver.lambda$resolve$0(PortalCandidateResolver.java:78)
        at java.util.Optional.map(Optional.java:215)
        at org.icgc.dcc.dev.server.portal.candidate.PortalCandidateResolver.resolve(PortalCandidateResolver.java:78)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.icgc.dcc.dev.server.portal.candidate.PortalCandidateResolver.resolve(PortalCandidateResolver.java:68)
        at org.icgc.dcc.dev.server.portal.PortalService.getCandidates(PortalService.java:90)
        at org.icgc.dcc.dev.server.portal.PortalController.getCandidates(PortalController.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)```
``````

**Comment by btiernay** [comment]
Fixed
